#!/bin/ash
START=99
STOP=99

result=$(ps | grep adm | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/adm restart
	
fi

result=$(ps | grep vsftpd | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/vsftpd restart
	
fi

result=$(ps | grep webshell | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/webshell restart
	
fi

result=$(ps | grep ss-redir | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/ss restart
	
fi

result=$(ps | grep aria2c | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/aria2 restart
	
fi