#!/bin/ash
START=99
STOP=99

result=$(ps | grep adm | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/adm start
	
fi

result=$(ps | grep vsftpd | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/vsftpd start
	
fi

result=$(ps | grep webshell | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/webshell start
	
fi

result=$(ps | grep ss-redir | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/ss start
	
fi

result=$(ps | grep aria2c | grep -v grep | wc -l)

if [ "$result" == "0" ]; then

	/etc/misstar/scripts/aria2 start
	
fi