#!/bin/ash
START=99
STOP=99

case "$1" in
"vsftpd")
	olduser=`uci get misstar.vsftpd.ftp_user`
	sed -i "/$olduser/"d /etc/passwd
	sed -i "/$olduser/"d /etc/shadow
	sed -i "/$2/"d /etc/passwd
	sed -i "/$2/"d /etc/shadow
	echo "$2:*:10086:10086:$2:$4:/bin/false" >> /etc/passwd
	echo "$2:*:0:0:99999:7:::" >> /etc/shadow
	echo -e "$3\n$3" | passwd $2
	uci set misstar.vsftpd.ftp_user=$2
	uci set misstar.vsftpd.ftp_password=$3
	uci commit misstar
	rm_enable=$(uci get misstar.vsftpd.rm_enable)
	if [ "$rm_enable" = '1' ];then
		status=`uci show firewall | grep vsftpd | wc -l`
		if [ "$status" = "1" ];then
			exit
		else
			uci set firewall.vsftpd=rule
			uci set firewall.vsftpd.src=wan
			uci set firewall.vsftpd.proto=tcp
			uci set firewall.vsftpd.target=ACCEPT
			uci set firewall.vsftpd.family=ipv4
			uci set firewall.vsftpd.dest_port=21
			uci commit firewall
			/etc/init.d/firewall restart
			/etc/misstar/scprits/Dayjob
		fi
	else
		status=`uci show firewall | grep vsftpd | wc -l`
		if [ "$status" = "0" ];then
			exit
		else
			uci delete firewall.vsftpd
			uci commit firewall
			/etc/init.d/firewall restart
			/etc/misstar/scprits/Dayjob
		fi
	fi
	 ;;
"adm")
	case "$2" in
		"start")
			echo "/etc/misstar/scripts/adm start"
			;;
		"stop")
			echo "/etc/misstar/scripts/adm stop"
			;;
		"status")
			status=`ps | grep adm | grep misstar | wc -l`
			echo $status
	 esac
	 ;;
"sshd")
	case "$2" in
		"enable")
			uci set firewall.sshd=rule
			uci set firewall.sshd.src=wan
			uci set firewall.sshd.proto=tcp
			uci set firewall.sshd.target=ACCEPT
			uci set firewall.sshd.family=ipv4
			uci set firewall.sshd.dest_port=22
			uci commit firewall
			/etc/init.d/firewall restart
			;;
		"disable")
			uci delete firewall.sshd
			uci commit firewall
			;;
		"status")
			status=`uci show firewall | grep sshd | wc -l`
			echo $status
	 esac
	 ;;
"web")
	case "$2" in
		"enable")
			sed -i '/set \$finalvar \"\$canproxy \$isluci\"/i\    set \$isluci "1"; #misstar' /etc/sysapihttpd/miwifi-webinitrd.conf
			uci set firewall.rmweb=rule
			uci set firewall.rmweb.src=wan
			uci set firewall.rmweb.proto=tcp
			uci set firewall.rmweb.target=ACCEPT
			uci set firewall.rmweb.family=ipv4
			uci set firewall.rmweb.dest_port=8098
			uci set firewall.aria=rule
			uci set firewall.aria.src=wan
			uci set firewall.aria.proto=tcp
			uci set firewall.aria.target=ACCEPT
			uci set firewall.aria.family=ipv4
			uci set firewall.aria.dest_port=10086
			uci set firewall.webshell=rule
			uci set firewall.webshell.src=wan
			uci set firewall.webshell.proto=tcp
			uci set firewall.webshell.target=ACCEPT
			uci set firewall.webshell.family=ipv4
			uci set firewall.webshell.dest_port=4200
			uci commit firewall
			;;
		"disable")
			sed -i '/misstar/d' /etc/sysapihttpd/miwifi-webinitrd.conf
			uci delete firewall.rmweb
			uci delete firewall.aria
			uci delete firewall.webshell
			uci commit firewall
			;;
		"status")
			status=`uci show firewall | grep sshd | wc -l`
			echo $status
	 esac
	 ;;
"ss")
	case "$2" in
		"status")
			status=`ps | grep -E "ss-redir|ssr-redir" | grep -v 'grep' | wc -l`
			if [ "$status" == "1" ];then   #进程存在，已运行
					node=$(uci get misstar.ss.node)
					localport=$(uci get misstar.ss.ss_local_port_$node)
					if [ "$localport" == "" ]	;then
						localport=$(uci get misstar.ss.ss_local_port_1)
					fi
					DNS_PORT=`expr $localport + 1`
					http_status=`curl  -s -w %{http_code} https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/openbookproject/OpenBookProject-default.png -k -o /dev/null --socks5 127.0.0.1:$DNS_PORT`
					if [ "$http_status" == "200" ];then
						echo -e "2\c"   #翻墙正常
					else
						echo -e "3\c"   
					fi
			else
				echo -e "1\c"
			fi
			;;
		"dnsstatus")
			status=`nslookup www.youtube.com > /dev/null 2>&1 ; echo $?`
			if [ "$status" == "0" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"addpac")
			echo $3 >> /etc/misstar/.config/pac_customize.conf
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"delpac")
			sed -i "/$3/d" /etc/misstar/.config/pac_customize.conf
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"addwhite")
			echo $3 >> /etc/misstar/.config/chnroute_customize.txt
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"delwhite")
			sed -i "/$3/d" /etc/misstar/.config/chnroute_customize.txt
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
	 esac
	 ;;
esac

