#!/bin/ash
START=99
STOP=99

case "$1" in
"vsftpd")
	olduser=`uci get misstar.vsftpd.ftp_user`
	sed -i "/$olduser/"d /etc/passwd
	sed -i "/$olduser/"d /etc/shadow
	sed -i "/$2/"d /etc/passwd
	sed -i "/$2/"d /etc/shadow
	echo "$2:*:10086:10086:$2:$4:/bin/false" >> /etc/passwd
	echo "$2:*:0:0:99999:7:::" >> /etc/shadow
	echo -e "$3\n$3" | passwd $2
	uci set misstar.vsftpd.ftp_user=$2
	uci set misstar.vsftpd.ftp_password=$3
	uci commit misstar
	 ;;
"adm")
	case "$2" in
		"start")
			echo "/etc/misstar/scripts/adm start"
			;;
		"stop")
			echo "/etc/misstar/scripts/adm stop"
			;;
		"status")
			status=`ps | grep adm | grep misstar | wc -l`
			echo $status
	 esac
	 ;;
"sshd")
	case "$2" in
		"enable")
			app_enable=$(uci get misstar.sshd.enable)
			if [ "$app_enable" = '1' ];then
				result=$(iptables -L | grep misstar-sshd | wc -l)
				if [ "$result" = '0' ];then
					iptables -A INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment "misstar-sshd"
				fi
			fi
			;;
		"disable")
			iptables -D INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment "misstar-kms" &> /dev/null
			;;
		"status")
			status=$(iptables -L | grep misstar-sshd | wc -l)
			echo $status
	 esac
	 ;;
"web")
	case "$2" in
		"enable")
			app_enable=$(uci get misstar.web.enable)
			if [ "$app_enable" = '1' ];then
				result=$(cat /etc/sysapihttpd/miwifi-webinitrd.conf | grep misstar | wc -l)
				if [ "$result" = '0' ];then
					sed -i '/set \$finalvar \"\$canproxy \$isluci\"/i\    set \$isluci "1"; #misstar' /etc/sysapihttpd/miwifi-webinitrd.conf
					/etc/init.d/sysapihttpd restart
					mount -o remount,rw /
					sed -i 's/string.upper(luci.sys.net.ip4mac(remote_addr))/luci.sys.net.ip4mac(remote_addr)/'       /usr/lib/lua/luci/view/web/setting/wan.htm
					sed -i 's/string.upper(luci.sys.net.ip4mac(remote_addr))/luci.sys.net.ip4mac(remote_addr)/'       /usr/lib/lua/luci/view/web/setting/ddns.htm 
				fi
				web_port=$(uci get misstar.web.web_port)
				if [ "$web_port" != '8098' ];then
					sed -i '/misstar/d' /etc/sysapihttpd/sysapihttpd.conf 
					sed -i "/8098/a\    listen ${web_port};#misstar" /etc/sysapihttpd/sysapihttpd.conf 
					/etc/init.d/sysapihttpd restart
				fi
				iptables -A INPUT -p tcp --dport $web_port -j ACCEPT -m comment --comment "misstar-web"
				result=$(iptables -L | grep misstar-aria2 | wc -l)
				if [ "$result" = '0' ];then
					iptables -A INPUT -p tcp --dport 10086 -j ACCEPT -m comment --comment "misstar-aria2"
				fi
					result=$(iptables -L | grep misstar-webshell | wc -l)
				if [ "$result" = '0' ];then
					iptables -A INPUT -p tcp --dport 4200 -j ACCEPT -m comment --comment "misstar-webshell"
				fi
			fi
			;;
		"disable")
			sed -i '/misstar/d' /etc/sysapihttpd/miwifi-webinitrd.conf
			sed -i '/misstar/d' /etc/sysapihttpd/sysapihttpd.conf 
			/etc/init.d/sysapihttpd restart
			iptables -D INPUT -p tcp --dport 8098 -j ACCEPT -m comment --comment "misstar-web" &> /dev/null
			iptables -D INPUT -p tcp --dport 10086 -j ACCEPT -m comment --comment "misstar-aria2" &> /dev/null
			iptables -D INPUT -p tcp --dport 4200 -j ACCEPT -m comment --comment "misstar-webshell" &> /dev/null
			;;
		"status")
			status=$(iptables -L | grep misstar-web | wc -l)
			echo $status
	 esac
	 ;;
"ss")
	case "$2" in
		"status")
			status=`ps | grep -E "ss-redir|ssr-redir" | grep -v 'grep' | wc -l`
			if [ "$status" == "1" ];then   #进程存在，已运行
					node=$(uci get misstar.ss.node)
					localport=$(uci get misstar.ss.ss_local_port_$node)
					if [ "$localport" == "" ]	;then
						localport=$(uci get misstar.ss.ss_local_port_1)
					fi
					DNS_PORT=`expr $localport + 1`
					http_status=`curl  -s -w %{http_code} https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/openbookproject/OpenBookProject-default.png -k -o /dev/null --socks5 127.0.0.1:$DNS_PORT`
					if [ "$http_status" == "200" ];then
						echo -e "2\c"   #翻墙正常
					else
						echo -e "3\c"   
					fi
			else
				echo -e "1\c"
			fi
			;;
		"dnsstatus")
			status=`nslookup www.youtube.com > /dev/null 2>&1 ; echo $?`
			if [ "$status" == "0" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"addpac")
			echo $3 >> /etc/misstar/.config/pac_customize.conf
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"delpac")
			sed -i "/$3/d" /etc/misstar/.config/pac_customize.conf
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"addwhite")
			echo $3 >> /etc/misstar/.config/chnroute_customize.txt
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
		"delwhite")
			sed -i "/$3/d" /etc/misstar/.config/chnroute_customize.txt
			status=$?
			if [ "$status" == "1" ]; then
				echo -e "1\c"
			else
				echo -e "0\c"
			fi
		;;
	 esac
	 ;;
esac

