#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

EXTRA_COMMANDS=" status  version"
EXTRA_HELP="        status  Get shadowsocks status
        version Get Misstar Tools Version"

## Check The Router Hardware Model 
mode=$(cat /proc/xiaoqiang/model)

if [ "$mode" = "R2D" -o "$mode" = "R1D" ];then
	Hardware_model="arm"
elif [ "$mode" = "R3" ];then
	Hardware_model="mips"
else
	echo "This Tools doesn't support XiaoMi Mini"
	exit
fi 
	
appname=vsftpd
ftp_getconfig() {
	vsftpd_enable=$(uci get misstar.$appname.enable)
	if [ "$vsftpd_enable" = '0' ];then
		echo "service vsftpd is disabeld!"
		exit
	fi
	
	AreadyRunning=$(ps | grep vsftpd | grep -v grep | grep -v scripts | wc -l)
	if [ "$AreadyRunning" != '0' ];then
		echo "vsftpd is aleady running,Exit..."
		exit
	fi
	rm_enable=$(uci get misstar.$appname.rm_enable)
	if [ "$AreadyRunning" == '1' ];then
		result=$(iptables -L | grep misstar-vsfptd | wc -l)
		if [ "$result" = '0' ];then
			iptables -A INPUT -p tcp --dport 21 -j ACCEPT -m comment --comment "misstar-vsftpd"
		fi
	fi
	root_enable=$(uci get misstar.$appname.root_enable)
	if [ "$root_enable" = '1' ];then
		echo "root" >> /etc/vsftpd.users
	else
		sed -i "/root/"d /etc/vsftpd.users
	fi
	
	anonymous_enable=$(uci get misstar.$appname.any_enable)
	if [ "$anonymous_enable" = '1' ];then
		sed -i 's/anonymous_enable=NO/anonymous_enable=YES/' /etc/misstar/.config/vsftpd.conf
	else
		sed -i 's/anonymous_enable=YES/anonymous_enable=NO/' /etc/misstar/.config/vsftpd.conf
	fi

	write_enable=$(uci get misstar.$appname.write_enable)
	if [ "$write_enable" = '1' ];then
		sed -i 's/write_enable=NO/write_enable=YES/' /etc/misstar/.config/vsftpd.conf
	else
		sed -i 's/write_enable=YES/write_enable=NO/' /etc/misstar/.config/vsftpd.conf
	fi
	
	cp -rf /etc/misstar/.config/vsftpd.conf /etc/
}
								

start() {
	ftp_getconfig
	mkdir -m 0755 -p /var/run/vsftpd
	service_start /etc/misstar/$Hardware_model/vsftpd
}

stop() {
	service_stop /etc/misstar/$Hardware_model/vsftpd
	iptables -D INPUT -p tcp --dport 21 -j ACCEPT -m comment --comment "misstar-vsftpd" &> /dev/null
}

status() {
	status=`ps | grep vsftpd | grep -v grep | wc -l`
	if [ "$status" = '2' ];then
		echo "service vsftpd is not running"
	else
		echo "service vsftpd is running"
	fi
}











