#!/bin/sh /etc/rc.common

START=99

EXTRA_COMMANDS=" status  version"
EXTRA_HELP="        status  Get shadowsocks status
        version Get Misstar Tools Version"

## Check The Router Hardware Model 
mode=$(cat /proc/xiaoqiang/model)

if [ "$mode" = "R2D" -o "$mode" = "R1D" ];then
	Hardware_model="arm"
elif [ "$mode" = "R3" ];then
	Hardware_model="mips"
else
	echo "This Tools doesn't support XiaoMi Mini"
	exit
fi 

appname=webshell
start() {
	adm_enable=$(uci get misstar.$appname.enable)
	if [ "$adm_enable" = '0' ];then
		echo "service Adm is disabeld!"
		exit
	fi
	AreadyRunning=$(ps | grep shellinabox | grep -v grep | wc -l)
	if [ "$AreadyRunning" != '0' ];then
		echo "Webshell is aleady running,Exit..."
		exit
	fi
    echo "running shellinaboxd..."
    service_start /etc/misstar/$Hardware_model/shellinaboxd -s /:LOGIN -u root &
    echo "ok!"
}
stop() {
    echo "stop shellinaboxd..."
    service_stop /etc/misstar/$Hardware_model/shellinaboxd
    echo "end!"
}
restart() {
    stop;sleep 2;start
}